### ISSUE TITLE
TensorBoardLogger.jl New Version Compatability

### ISSUE THREAD

**Issue by PeggyYuchunWang** [JuliaPOMDP/DeepQLearning.jl#16]
New version https://github.com/PhilipVinc/TensorBoardLogger.jl/commit/e9cbedfd51beafd8722e946f20b1340725fedec8 changes from Logger() object to TBLogger() object.

**Comment by MaximeBouton** [comment]
Unfortunately this package is not registered so we cannot do version control easily, if it is just a name change it should be an easy fix though, I will look into it tomorrow.

**Comment by PeggyYuchunWang** [comment]
It's not just name :( it's also the types of the functions as well, specifically log_value()
