### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by wbrannon** [JuliaPOMDP/DeepQLearning.jl#23]
The following error is thrown when attempting to use DeepQLearning.jl: 
`ERROR: LoadError: LoadError: UndefVarError: Tracker not defined`

This appears to be a Flux issue.

**Comment by MaximeBouton** [comment]
I think it should be fixed by https://github.com/JuliaPOMDP/DeepQLearning.jl/commit/2a9c3d32f967c99c84173fc04f571a743f55e91c

`] add DeepQLearning#master`

or 
`]add Flux@v0.8.3`

can fix the issue otherwise.
