### ISSUE TITLE
Type of the discount factor.

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/DeepQLearning.jl#28]
If the `discount` function returns a `Float64` , then everything gets promoted to `Float64`. 

We could: 
- convert to Float32 here: https://github.com/JuliaPOMDP/DeepQLearning.jl/blob/master/src/solver.jl#L196
- write something in the doc about it

**Comment by rejuvyesh** [comment]
We should convert there as per the network.
