### ISSUE TITLE
Use only RLInterface.jl interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/DeepQLearning.jl#29]
One of my students discovered that this package uses `POMDPs.actionindex`. Would it be possible to make the package only use functions from the RLInterface.jl interface? (i.e. we would need to construct our own action map)

**Comment by MaximeBouton** [comment]
It is using `actionindex` to take slices of the batches of q values. It is listed in the requirements I believe.
As soon as the action is taken, it is converted as an integer and stored that way in the buffer. 

Where would the custom action map definition be living? Are you suggesting to extend RLInterface or to use the existing `actions` function.
The solver would need to have access to this ordering somehow.

**Comment by zsunberg** [comment]
I think we would just use the existing actions function. The action map would be internal to the solver. I'll make a PR.

**Comment by zsunberg** [comment]
PR: #30
