### ISSUE TITLE
DQExperience should support AbstractArrays

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/DeepQLearning.jl#31]
From Piazza:

> I'm troubleshooting in the deep Q learning package and I'm having a problem with the DQExperience object. The object is defined in 'prioritized_experience_replay.jl' and is as follows:
> 
> ```julia
> struct DQExperience{N <: Real,T <: Real, Q}
> s::Array{T, Q}
> a::N
> r::T
> sp::Array{T, Q}
> done::Bool
> end
> ``` 
> 
> The problem is that our states are defined using the StaticArrays type
>  
> Is there a reason that state is constrained to an array of real numbers? Is there a way to create a subclass of DQExperience or something that allows or the StaticArrays type?

**Comment by MaximeBouton** [comment]
It could support `AbstractArrays`, one can use the `convert_s`/`convert_o` function as the work around. 
I will try to make a PR.
