### ISSUE TITLE
Question: How would you make a decay schedule for prioritized replay alpha/beta? 

### ISSUE THREAD

**Issue by danortega2014** [JuliaPOMDP/DeepQLearning.jl#60]

**Comment by MaximeBouton** [comment]
Hi, this feature is not supported, if you want to implement it and submit a PR you are welcome to. 

I would suggest modifying the prioritized replay API and specifically the `add_exp!` function. https://github.com/JuliaPOMDP/DeepQLearning.jl/blob/master/src/prioritized_experience_replay.jl#L65
